# Generated by Django 4.0 on 2022-01-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0002_laptop_product_image_laptop_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_pdf',
            field=models.FileField(upload_to='images/'),
        ),
    ]
