# Generated by Django 4.0 on 2022-01-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0003_alter_laptop_product_image_alter_laptop_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='product_image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_pdf',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
